In [4]:
import numpy as np
def cpca(X,d_): #X: list of (d_v,n)
    X = np.concatenate(X)
    X = X-X.mean(axis=1).reshape(-1,1)
    cov_X = X.dot(X.T)
    eigenval,eigenvec = np.linalg.eig(cov_X)    
    select_vec = eigenvec[:,np.partition(eigenval,-d_)[-d_:]]
    out = select_vec.T.dot(X)
    return out



a = np.array([[1,2],[3,4]])
b = np.random.rand(3,4)
# np.concatenate([a,b])
a-a.mean(1)
b-b.mean(1).reshape(-1,1)
np.linalg.eig(b.dot(b.T))



(array([2.75092348, 0.34061695, 0.05694412]),
 array([[ 0.66376492,  0.73805594,  0.12120052],
        [ 0.34401528, -0.15737586, -0.92568155],
        [ 0.66413073, -0.65612976,  0.3583631 ]]))

In [5]:
import tarfile
import os
from tqdm import tqdm
import numpy as np
def untar(fname, dirs):
    """
    解压tar.gz文件
    :param fname: 压缩文件名
    :param dirs: 解压后的存放路径
    :return: bool
    """
    try:
        t = tarfile.open(fname)
        t.extractall(path = dirs)
        return True
    except Exception as e:
        print(e)
        return False

# untar('datasets/msrcorid.tar.gz','./datasets/')
from PIL import Image
def read_imgs():
    path = 'datasets/msrcorid'
    filepaths = []
    img_arrays = []
    labels = []
    for root, dirs, files in tqdm(os.walk(path)):
        # print(dirnames)     
        for file in files:
            if(file.endswith('JPG')):                         # 遍历文件
                file_path = os.path.join(root, file)
                img = np.asarray(Image.open(file_path))
                img_arrays.append(img.transpose((2,0,1)).reshape((3,-1,1)))
                labels.append(file[:3])   # 获取文件绝对路径  
                filepaths.append(file_path)            # 将文件路径添加进列表
        # for dir in dirs:                           # 遍历目录下的子目录
        #     dir_path = os.path.join(root, dir)     # 获取子目录路径
        #     all_files_path(dir_path)               # 递归调用
    return img_arrays,labels
img_arrays,labels = read_imgs()
color_mean = np.concatenate(img_arrays,axis = 2).mean(axis=1)
color_var = np.concatenate(img_arrays,axis = 2).var(axis=1)
color_skew = np.concatenate(img_arrays,axis = 2).skew(axis=1)
# img_tensor = np.concatenate(img_arrays,axis =2)

0it [00:00, ?it/s]

45it [00:33,  1.33it/s]


MemoryError: Unable to allocate 29.7 GiB for an array with shape (3, 307200, 4323) and data type float64

In [6]:
color_mean

array([[141.20790365, 110.08561849,  97.76833984, ...,  72.16966146,
         87.78776693,  88.09317383],
       [139.88450846, 110.74549805,  98.13979167, ...,  65.54639974,
         73.41256185,  77.23255208],
       [133.16296224,  99.32343099,  89.29935221, ...,  57.67697591,
         62.77745117,  69.35708008]])