In [ ]:
import numpy as np
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[2,3,2]])
U,sigma,VT = np.linalg.svd(data)
print(U,U.shape)
print(VT,VT.shape)
print(sigma)

In [ ]:
import numpy as np
mat = np.random.rand(100,400) #(d,n)

def pca(mat):
    mat = mat-mat.mean(axis=1).reshape(-1,1)
    cov = np.dot(mat,mat.T)
    eigval,eigvec = np.linalg.eig(cov)
    idx = np.argpartition(eigval,-50)[-50:]
    w = eigvec[:,idx] #
    out = w.T.dot(mat)
    print(w.shape)
    print(np.rint(w.T.dot(w)))#validate that W*W.T=I
pca(mat)

In [ ]:

import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6],[7,8,9]])
aa = np.array([a,a])
b = np.array([1,2])
# print(aa)
# np.linalg.multi_dot([aa,b])
# np.diag(a.sum(axis=1))
# np.sqrt(a)
# np.linalg.inv(np.sqrt(a)).dot(np.sqrt(a))
u,s,vh=np.linalg.svd(a)
print(u.shape,s.shape,vh.shape)
u[:,:2].dot(np.diag(s[:2])).dot(vh[:2,:])
# np.concatenate([a,a])

`calculate pairwise similarity`

In [ ]:
import numpy as np
a = np.array([[1,1],[2,2],[3,3]]) #3,2
b = np.array([[3,3],[4,4]]) #2,2
a_til = np.tile(np.expand_dims(a,1),[1,2,1])
b_til = np.tile(np.expand_dims(b,0),[3,1,1])
np.square(a_til-b_til).sum(axis=-1)

In [ ]:
import numpy as np
a = np.array([[1,1],[2,2],[3,3]])
b = np.array([[1],[2],[3]])
a*b
diag = 1/np.diagonal(np.array([[1,2],[3,4]])).reshape(-1,1)
diag

a = np.array([[1,2],[3,4]])
aa = np.array([a,a,a])
sum([a,a,a])
np.where(a[:,1]>0,a[:,1],0)
np.random.rand()+1
1e-4

In [ ]:
import numpy as np
k = np.array([0.5,0.7,0.3,1,0.9])
for p in np.linspace(-0.9,0.9,10000):
    sum_ = np.where(k+p>0,k+p,0).sum()
    if(np.abs(sum_-1)<1e-2):
        break
    
print(p,sum_)

In [ ]:
import numpy as np
from PIL import Image
img = Image.open('101_0108.JPG')
img_ = np.asarray(img.convert('L')) 
print(type(img_ ))
# Image.fromarray(img_).save('1.png')
Image.fromarray(img_).show()

`reshape tensor or array`

In [1]:
import numpy  as np
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a.transpose(2,0,1).shape

b = np.random.rand(3,3,1)
c = np.random.rand(3,3,1)
np.concatenate([b,c],axis=2)
np.expand_dims(b,axis=1).shape
a = np.arange(12).reshape(2,3,2)
b.squeeze()

array([[0.43289955, 0.14087993, 0.65887636],
       [0.70675956, 0.83891944, 0.62397878],
       [0.43292076, 0.52360927, 0.27626852]])

In [ ]:
import scipy.io as scio
filepath =  './datasets/data sets/MSRC-v1.mat'
data = scio.loadmat(filepath)
data['X'][0][1].shape

In [48]:
%load_ext autoreload
%autoreload 2
from utils import *
X,labels=read_data('datasets/data sets/MSRC-v1.mat')
X = [X[0,i].T for  i  in range(X.shape[1])]
from models import MSE
model_MSE = MSE()
# Y = model_MSE.mse(X,0.5,120,10000000,500)
X,labels=read_data('datasets/data sets/BBC.mat')
X = [X[0,i] for i in range(X.shape[1])]
X

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


[<685x4659 sparse matrix of type '<class 'numpy.float64'>'
 	with 37493 stored elements in Compressed Sparse Column format>,
 <685x4633 sparse matrix of type '<class 'numpy.float64'>'
 	with 37960 stored elements in Compressed Sparse Column format>,
 <685x4665 sparse matrix of type '<class 'numpy.float64'>'
 	with 37315 stored elements in Compressed Sparse Column format>,
 <685x4684 sparse matrix of type '<class 'numpy.float64'>'
 	with 37227 stored elements in Compressed Sparse Column format>]

: 

In [ ]:

from sklearn.metrics.cluster import normalized_mutual_info_score
from sklearn.cluster import KMeans
km = KMeans(n_clusters=7).fit(Y.T)
centers = km.cluster_centers_
print(centers.shape)
source   = Y.T
dist = dist_2m_sq(source,centers)
print(dist.shape)
dist/dist.sum(1).reshape(-1,1)
# nmi = normalized_mutual_info_score(labels.squeeze(),pred)
# print(nmi)

In [21]:
kmeans_cluster_prob(Y)[0]

d:\Soft\Anaconda\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
d:\Soft\Anaconda\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


array([0.16962335, 0.10816815, 0.07436421, 0.18710795, 0.10984313,
       0.18670049, 0.16419271])

In [34]:
np.array([[1,2,3],[4,5,6],[7,8,9]])*np.array([[1,2,3]])
np.array([[1,2,3],[4,5,6],[7,8,9]]).sum(1)
np.array([[1,2,3],[4,5,6],[7,8,9]])/np.array([[1,2,3]])
np.array([[1,2,3],[4,5,6],[7,8,9]]).sum(0).reshape(-1,1)
np.array([[5,2,3],[4,7,6],[7,8,9]]).argmax(1)


array([0, 1, 2], dtype=int64)