In [9]:
import numpy as np
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[2,3,2]])
U,sigma,VT = np.linalg.svd(data)
print(U,U.shape)
print(VT,VT.shape)
print(sigma)

[[-1.39047179e-01  7.57095860e-01 -3.27828828e-01 -2.41327587e-01
   4.91691972e-01]
 [-3.39672716e-01  4.09202847e-01 -1.31055240e-01  6.88255674e-01
  -4.75714334e-01]
 [-5.40298254e-01  6.13098339e-02  6.57183488e-02 -6.52528587e-01
  -5.23647250e-01]
 [-7.40923791e-01 -2.86583179e-01  2.62491937e-01  2.05600500e-01
   5.07669611e-01]
 [-1.56198786e-01 -4.16497388e-01 -8.95618147e-01  4.18641467e-16
   5.66048060e-16]] (5, 5)
[[-0.50435418 -0.57868533 -0.64089792]
 [-0.63484581 -0.25460693  0.72948346]
 [ 0.58531843 -0.77478939  0.23896389]] (3, 3)
[25.77843465  1.37946958  0.7545666 ]


In [74]:
import numpy as np
mat = np.random.rand(100,400) #(d,n)

def pca(mat):
    mat = mat-mat.mean(axis=1).reshape(-1,1)
    cov = np.dot(mat,mat.T)
    eigval,eigvec = np.linalg.eig(cov)
    idx = np.argpartition(eigval,-50)[-50:]
    w = eigvec[:,idx] #
    out = w.T.dot(mat)
    print(w.shape)
    print(np.rint(w.T.dot(w)))#validate that W*W.T=I
pca(mat)

(100, 50)
[[ 1.  0.  0. ... -0.  0.  0.]
 [ 0.  1.  0. ... -0. -0. -0.]
 [ 0.  0.  1. ...  0. -0. -0.]
 ...
 [-0. -0.  0. ...  1. -0.  0.]
 [ 0. -0. -0. ... -0.  1. -0.]
 [ 0. -0. -0. ...  0. -0.  1.]]


In [96]:
a1 = np.array([2,1,4,3])
idx = np.argpartition(a1,3)
print(idx)
a1[idx]

[1 0 3 2]


array([1, 2, 3, 4])

In [35]:
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6],[7,8,9]])
aa = np.array([a,a])
b = np.array([1,2])
# print(aa)
# np.linalg.multi_dot([aa,b])
# np.diag(a.sum(axis=1))
# np.sqrt(a)
# np.linalg.inv(np.sqrt(a)).dot(np.sqrt(a))
u,s,vh=np.linalg.svd(a)
print(u,s,vh)
u[:,:2].dot(np.diag(s[:2])).dot(vh[:2,:])
np.concatenate([a,a])

[[-0.19869223  0.78348882  0.51665399 -0.28237444]
 [-0.38643091  0.36148465 -0.25435979  0.8095067 ]
 [-0.48030025  0.15048257 -0.69416159 -0.51459339]
 [-0.76190828 -0.48252369  0.43186739 -0.01253887]] [1.82661240e+01 1.16134126e+00 2.35555756e-16] [[-0.47150364 -0.57154301 -0.67158239]
 [-0.78167618 -0.08168181  0.61831256]
 [ 0.40824829 -0.81649658  0.40824829]]


array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [3, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])